import { unicodeToZawgyi } from "../../lib/zawgyi";
import { useLanguageStore } from "../../stores/languageStore";
import type { DateRange } from "./dashboardMetrics";

const en = {
  dashboard: "Dashboard",
  allShops: "All Shops",
  allShopsScope: "All shops",
  unknownShop: "Unknown shop",
  unknownUser: "Unknown user",
  shop: "Shop",
  today: "Today",
  week: "Week",
  month: "Month",
  businessControlFor: "business control for",
  operations: "operations",
  revenue: "Revenue",
  costInvestment: "Cost / Investment",
  orders: "Orders",
  aov: "AOV",
  profit: "Profit",
  margin: "Margin",
  profitMargin: "Profit / Margin",
  supplierDebt: "Supplier Debt",
  revenueCostProfitTrend: "Revenue, Cost & Profit Trend",
  validSales: "Valid sales",
  average: "average",
  receivedPosUnpaidPartial: "received PO(s) unpaid or partial",
  shopPerformance: "Shop Performance",
  revenueByShop: "Revenue by Shop",
  openShifts: "Open shifts",
  noShopSalesInRange: "No shop sales in this range.",
  noRevenueToChart: "No revenue to chart in this range.",
  lowStockAcrossShops: "Low Stock Across Shops",
  lowStock: "Low stock",
  outOfStock: "Out of stock",
  threshold: "Threshold",
  left: "left",
  noLowOrOutStock: "No low or out-of-stock items.",
  pendingApprovals: "Pending Approvals",
  noPendingRefundVoidApprovals: "No pending refund or void approvals.",
  activeStaffOpenShifts: "Active Staff / Open Shifts",
  open: "Open",
  since: "since",
  noOpenShifts: "No open shifts in this scope.",
  actionQueue: "Action Queue",
  poReceipts: "PO receipts",
  transfers: "Transfers",
  supplierDebtBySupplier: "Supplier Debt by Supplier",
  supplierDebtByShop: "Supplier Debt by Shop",
  openPoCount: "open PO(s)",
  noOutstandingSupplierDebt: "No outstanding received supplier debt.",
  recentAuditActivity: "Recent Audit Activity",
  noAuditActivity: "No audit activity in this range.",
  recentSales: "Recent Sales",
  noSalesInRange: "No sales in this range.",
  activeShiftCash: "Active Shift / Cash",
  locked: "Locked",
  expected: "Expected",
  shiftPermissionRequired: "Shift permission required",
  actionNeeded: "Action Needed",
  currentOpenItems: "Current open items",
  topSellingProducts: "Top Selling Products",
  sold: "sold",
  noProductSalesInRange: "No product sales in this range.",
  needsPayment: "Needs payment",
  pendingRefundVoidApprovals: "Pending Refund/Void Approvals",
  requested: "Requested",
  noPendingApprovals: "No pending approvals.",
  inventoryAlerts: "Inventory Alerts",
  pendingPoReceipts: "Pending PO Receipts",
  noApprovedPosWaitingReceipt: "No approved POs waiting for receipt.",
  supplier: "Supplier",
  pendingTransfers: "Pending Transfers",
  noPendingTransfersForShop: "No pending transfers for this shop.",
  pending: "Pending",
  to: "to",
  salesByCategory: "Sales by Category",
  noSalesDataForPeriod: "No sales data for this period.",
  noCategorySalesForPeriod: "No category sales for this period.",
  noCategorySalesInRange: "No category sales in this range.",
  cashVsOtherSales: "Cash vs Other Sales",
  cash: "Cash",
  other: "Other",
  assignedShop: "Assigned shop",
  ownShiftSummary: "own-shift summary",
  pos: "POS",
  salesHistory: "Sales History",
  shiftSummary: "Shift Summary",
  shiftStatus: "Shift Status",
  noOpenShift: "No open shift",
  started: "Started",
  startShiftBeforePos: "Start a shift before POS",
  ownShiftSales: "Own Shift Sales",
  voidSalesExcluded: "VOID sales excluded",
  ownOrders: "Own Orders",
  voided: "voided",
  expectedCash: "Expected Cash",
  cashSales: "cash sales",
  recentOwnSales: "Recent Own Sales",
  noSalesForCurrentScope: "No sales for your current scope.",
  requests: "Requests",
  noPendingRefundVoidRequests: "No pending refund or void requests.",
  normal: "Normal",
  voidSale: "Void",
  partialRefund: "Partial refund",
  voidRequest: "Void request",
  dashboardUnavailable: "Dashboard unavailable",
  signInAgain: "Sign in again to load dashboard data.",
  noShopAssigned: "No shop assigned",
  noShopAssignedMessage:
    "Your account is not assigned to a shop, so there is no dashboard data to show. Contact your administrator.",
} as const;

const my: Record<keyof typeof en, string> = {
  dashboard: "ဒက်ရှ်ဘုတ်",
  allShops: "ဆိုင်အားလုံး",
  allShopsScope: "ဆိုင်အားလုံး",
  unknownShop: "မသိသောဆိုင်",
  unknownUser: "မသိသောအသုံးပြုသူ",
  shop: "ဆိုင်",
  today: "ယနေ့",
  week: "အပတ်",
  month: "လ",
  businessControlFor: "လုပ်ငန်းထိန်းချုပ်မှု",
  operations: "နေ့စဉ်လုပ်ငန်းများ",
  revenue: "ဝင်ငွေ",
  costInvestment: "ကုန်ကျစရိတ် / ရင်းနှီးမြှုပ်နှံမှု",
  orders: "အော်ဒါ",
  aov: "ပျမ်းမျှအော်ဒါ",
  profit: "အမြတ်",
  margin: "အမြတ်နှုန်း",
  profitMargin: "အမြတ် / အမြတ်နှုန်း",
  supplierDebt: "ပေးသွင်းသူကြွေးမြီ",
  revenueCostProfitTrend: "ဝင်ငွေ၊ ကုန်ကျစရိတ်နှင့် အမြတ် လမ်းကြောင်း",
  validSales: "မှန်ကန်သောရောင်းချမှု",
  average: "ပျမ်းမျှ",
  receivedPosUnpaidPartial: "လက်ခံပြီး မပေးချေရသေး/တစ်စိတ်တစ်ပိုင်းပေးချေထားသော PO",
  shopPerformance: "ဆိုင်စွမ်းဆောင်ရည်",
  revenueByShop: "ဆိုင်အလိုက်ဝင်ငွေ",
  openShifts: "ဖွင့်ထားသောအလုပ်ချိန်များ",
  noShopSalesInRange: "ဤကာလအတွင်း ဆိုင်ရောင်းချမှု မရှိပါ။",
  noRevenueToChart: "ဤကာလအတွင်း ဂရပ်ပြရန် ဝင်ငွေမရှိပါ။",
  lowStockAcrossShops: "ဆိုင်များအလိုက် စတော့နည်း",
  lowStock: "စတော့နည်း",
  outOfStock: "စတော့ကုန်",
  threshold: "အနည်းဆုံးပမာဏ",
  left: "ကျန်",
  noLowOrOutStock: "စတော့နည်း သို့မဟုတ် စတော့ကုန် ပစ္စည်းမရှိပါ။",
  pendingApprovals: "စောင့်ဆိုင်းနေသောအတည်ပြုချက်များ",
  noPendingRefundVoidApprovals: "စောင့်ဆိုင်းနေသော ပြန်အမ်း/ပယ်ဖျက် အတည်ပြုချက် မရှိပါ။",
  activeStaffOpenShifts: "လက်ရှိဝန်ထမ်း / ဖွင့်ထားသောအလုပ်ချိန်",
  open: "ဖွင့်ထားသည်",
  since: "မှစ၍",
  noOpenShifts: "ဤအပိုင်းတွင် ဖွင့်ထားသောအလုပ်ချိန် မရှိပါ။",
  actionQueue: "လုပ်ဆောင်ရန်များ",
  poReceipts: "PO လက်ခံရန်",
  transfers: "လွှဲပြောင်းမှုများ",
  supplierDebtBySupplier: "ပေးသွင်းသူအလိုက်ကြွေးမြီ",
  supplierDebtByShop: "ဆိုင်အလိုက်ပေးသွင်းသူကြွေးမြီ",
  openPoCount: "ဖွင့်ထားသော PO",
  noOutstandingSupplierDebt: "လက်ခံပြီး ကျန်ရှိသော ပေးသွင်းသူကြွေးမြီ မရှိပါ။",
  recentAuditActivity: "မကြာသေးမီ စစ်ဆေးမှုလှုပ်ရှားမှု",
  noAuditActivity: "ဤကာလအတွင်း စစ်ဆေးမှုလှုပ်ရှားမှု မရှိပါ။",
  recentSales: "မကြာသေးမီရောင်းချမှုများ",
  noSalesInRange: "ဤကာလအတွင်း ရောင်းချမှုမရှိပါ။",
  activeShiftCash: "လက်ရှိအလုပ်ချိန် / ငွေသား",
  locked: "ပိတ်ထားသည်",
  expected: "မျှော်မှန်း",
  shiftPermissionRequired: "အလုပ်ချိန်ခွင့်ပြုချက်လိုအပ်သည်",
  actionNeeded: "လုပ်ဆောင်ရန်လိုအပ်",
  currentOpenItems: "လက်ရှိဖွင့်ထားသောအရာများ",
  topSellingProducts: "အရောင်းရဆုံးပစ္စည်းများ",
  sold: "ရောင်းပြီး",
  noProductSalesInRange: "ဤကာလအတွင်း ပစ္စည်းရောင်းချမှု မရှိပါ။",
  needsPayment: "ပေးချေရန်လိုအပ်",
  pendingRefundVoidApprovals: "ပြန်အမ်း/ပယ်ဖျက် အတည်ပြုရန်",
  requested: "တောင်းဆိုထားသည်",
  noPendingApprovals: "စောင့်ဆိုင်းနေသော အတည်ပြုချက် မရှိပါ။",
  inventoryAlerts: "စတော့သတိပေးချက်များ",
  pendingPoReceipts: "လက်ခံရန်စောင့်နေသော PO",
  noApprovedPosWaitingReceipt: "လက်ခံရန်စောင့်နေသော အတည်ပြုပြီး PO မရှိပါ။",
  supplier: "ပေးသွင်းသူ",
  pendingTransfers: "စောင့်ဆိုင်းနေသောလွှဲပြောင်းမှုများ",
  noPendingTransfersForShop: "ဤဆိုင်အတွက် စောင့်ဆိုင်းနေသော လွှဲပြောင်းမှု မရှိပါ။",
  pending: "စောင့်ဆိုင်းနေသည်",
  to: "သို့",
  salesByCategory: "အမျိုးအစားအလိုက်ရောင်းအား",
  noSalesDataForPeriod: "ဤကာလအတွင်း ရောင်းချမှုဒေတာ မရှိပါ။",
  noCategorySalesForPeriod: "ဤကာလအတွင်း အမျိုးအစားအလိုက် ရောင်းချမှု မရှိပါ။",
  noCategorySalesInRange: "ဤကာလအတွင်း အမျိုးအစားအလိုက်ရောင်းအား မရှိပါ။",
  cashVsOtherSales: "ငွေသားနှင့် အခြားရောင်းချမှု",
  cash: "ငွေသား",
  other: "အခြား",
  assignedShop: "တာဝန်ပေးထားသောဆိုင်",
  ownShiftSummary: "ကိုယ်ပိုင်အလုပ်ချိန်အကျဉ်းချုပ်",
  pos: "အရောင်းစက်",
  salesHistory: "ရောင်းချမှုမှတ်တမ်း",
  shiftSummary: "အလုပ်ချိန်အကျဉ်းချုပ်",
  shiftStatus: "အလုပ်ချိန်အခြေအနေ",
  noOpenShift: "ဖွင့်ထားသောအလုပ်ချိန် မရှိပါ",
  started: "စတင်ခဲ့သည်",
  startShiftBeforePos: "POS မသုံးမီ အလုပ်ချိန်ဖွင့်ပါ",
  ownShiftSales: "ကိုယ်ပိုင်အလုပ်ချိန်ရောင်းအား",
  voidSalesExcluded: "ပယ်ဖျက်ထားသောရောင်းချမှုများ မပါ",
  ownOrders: "ကိုယ်ပိုင်အော်ဒါများ",
  voided: "ပယ်ဖျက်ပြီး",
  expectedCash: "မျှော်မှန်းငွေသား",
  cashSales: "ငွေသားရောင်းအား",
  recentOwnSales: "မကြာသေးမီ ကိုယ်ပိုင်ရောင်းချမှုများ",
  noSalesForCurrentScope: "လက်ရှိအပိုင်းအတွက် ရောင်းချမှုမရှိပါ။",
  requests: "တောင်းဆိုချက်များ",
  noPendingRefundVoidRequests: "စောင့်ဆိုင်းနေသော ပြန်အမ်း/ပယ်ဖျက် တောင်းဆိုချက် မရှိပါ။",
  normal: "ပုံမှန်",
  voidSale: "ပယ်ဖျက်",
  partialRefund: "တစ်စိတ်တစ်ပိုင်းပြန်အမ်း",
  voidRequest: "ပယ်ဖျက်ရန်တောင်းဆိုချက်",
  dashboardUnavailable: "ဒက်ရှ်ဘုတ် မရရှိနိုင်ပါ",
  signInAgain: "ဒက်ရှ်ဘုတ်ဒေတာ တင်ရန် ပြန်လည်ဝင်ရောက်ပါ။",
  noShopAssigned: "ဆိုင်တာဝန်ပေးထားခြင်း မရှိပါ",
  noShopAssignedMessage:
    "သင့်အကောင့်ကို ဆိုင်တစ်ဆိုင်နှင့် မချိတ်ထားသောကြောင့် ဒက်ရှ်ဘုတ်ဒေတာ မပြနိုင်ပါ။ စီမံခန့်ခွဲသူကို ဆက်သွယ်ပါ။",
};

export type DashboardCopyKey = keyof typeof en;

export const useDashboardCopy = () => {
  const { language, isZawgyi } = useLanguageStore();
  return (key: DashboardCopyKey): string => {
    const text = language === "my" ? my[key] : en[key];
    return language === "my" && isZawgyi ? unicodeToZawgyi(text) : text;
  };
};

export const rangeLabel = (
  copy: (key: DashboardCopyKey) => string,
  range: DateRange
): string => copy(range);
